# Generated by Django 5.2.5 on 2025-08-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticket_ticketmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
